name: neurocare
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.3.0
  flutter_form_builder: ^9.7.0
  form_builder_validators: ^11.1.1
  smooth_page_indicator: ^1.2.0+3
  intl: ^0.19.0
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/

